{
 "title": "Unbound-dns",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "unbound-dns" }
  ]
 },
 "panels": [
  {
   "title": "Most popular domains in the last 5000 queries",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"} |~ `info: (?:\\d{1,3}\\.){3}\\d{1,3} .+ (A|HTTPS) IN` \n| regexp `info: (?:\\d{1,3}\\.){3}\\d{1,3} (?P<domain>.+) (A|HTTPS) IN` \n| line_format `{{.domain}}`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Request logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"} |= ``"
    }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |~ ` A ` [$__range])",
     "legendFormat": "A"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `AAAA` [$__range])",
     "legendFormat": "AAAA"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `HTTPS` [$__range])",
     "legendFormat": "HTTPS"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `SOA` [$__range])",
     "legendFormat": "SOA"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `SRV` [$__range])",
     "legendFormat": "SRV"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `PTR` [$__range])",
     "legendFormat": "PTR"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} |= `TXT` [$__range])",
     "legendFormat": "TXT"
    }
   ]
  }
 ]
}